language: python # => 1
python: # => 2
  - "3.6"
env: # => 3
  - DJANGO=1.11
install: # => 4
  - pip install -r requirements.txt
  - pip install coveralls
script: # => 5
  #- python manage.py test
  - coverage run --source='.' manage.py test
after_script: # => 6
  - coveralls

