# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-29 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolistapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_task',
            field=models.DateField(blank=True, null=True),
        ),
    ]
